import { CollectionItem } from './collectionsData';

/**
 * ==============================================================================
 * CERTIFICATES DATASET
 * Add or edit your certificates here.
 * Format:
 * {
 *   id: number,
 *   title: 'Certificate Name',
 *   tag: 'CATEGORY TAG',
 *   description: 'Details about the certification',
 *   image: 'Image URL or path',
 *   date: 'Year'
 * }
 * ==============================================================================
 */
export const certificatesData: CollectionItem[] = [
{
  id: 1,
  title: "CompTIA PenTest+: Reconnaissance & Enumeration",
  tag: "COURSE",
  description: "CompTIA PenTest+: Reconnaissance & Enumeration — Infosys Springboard",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007896/Reconnaissance-Enumeration.jpg",
  date: "2026",
},
{
  id: 2,
  title: "Introduction to AI-Assisted Vibe Coding",
  tag: "WEBINAR",
  description: "Introduction to AI-Assisted Vibe Coding — Kerala Startup Mission",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007895/vibe_coding.jpg",
  date: "2026",
},
{
  id: 3,
  title: "Figma Essentials For Modern Design",
  tag: "WEBINAR",
  description: "Figma Essentials For Modern Design — Kerala Startup Mission",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007896/Figma.jpg",
  date: "2026",
},
{
  id: 4,
  title: "Creating Comics: From Ideas to Pages",
  tag: "WEBINAR",
  description: "Creating Comics: From Ideas to Pages — Kerala Startup Mission",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007896/Creating-Comics-From-Ideas-to-Pages.jpg",
  date: "2026",
},
{
  id: 5,
  title: "Personal Branding for Career Succes",
  tag: "WEBINAR",
  description: "Personal Branding for Career Succes — Kerala Startup Mission",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007896/Personal-Branding.jpg",
  date: "2026",
},
{
  id: 6,
  title: "Fundamentals of the Prompt Engineering",
  tag: "WEBINAR",
  description: "Fundamentals of the Prompt Engineering — Kerala Startup Mission",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007896/Prompt-Engineering.jpg",
  date: "2026",
},
{
  id: 7,
  title: "Professional Resume & Portfolio Development",
  tag: "WEBINAR",
  description: "Professional Resume & Portfolio Development — Kerala Startup Mission",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007897/Resume-Portfolio_Development.jpg",
  date: "2026",
},
{
  id: 8,
  title: "CompTIA Network+: Well-known Ports & Protocols",
  tag: "COURSE",
  description: "CompTIA Network+: Well-known Ports & Protocols — Infosys Springboard",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007896/CompTIA2.jpg",
  date: "2026",
},
{
  id: 9,
  title: "CompTIA Network+: Network Types",
  tag: "COURSE",
  description: "CompTIA Network+: Network Types — Infosys Springboard",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007897/CompTIA.jpg",
  date: "2026",
},
{
  id: 10,
  title: "IT Networking Fundamentals for Complete Beginners",
  tag: "COURSE",
  description: "IT Networking Fundamentals for Complete Beginners — Udemy",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007897/It-Networking-Fundamentals.jpg",
  date: "2026",
},
{
  id: 11,
  title: "General Networking - Networking and Security Course",
  tag: "COURSE",
  description: "General Networking - Networking and Security Course — Infosys Springboard",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007897/General_Networking.jpg",
  date: "2026",
},
{
  id: 12,
  title: "Attended Online Webinar on Zero to Hero in 6 Months",
  tag: "WORKSHOP",
  description: "Attended Online Webinar on Zero to Hero in 6 Months — Offenso Hackers Academy",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007898/zero_to_hero.jpg",
  date: "2026",
},
{
  id: 13,
  title: "Participation in IEDC Startup Summit 2026",
  tag: "EVENT",
  description: "Participation in IEDC Startup Summit 2026 — Kerala Startup Mission",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007909/IEDC_Startup_Summit_2026.jpg",
  date: "2026",
},
{
  id: 14,
  title: "Complete UNIX & Linux OS Fundamentals Training",
  tag: "COURSE",
  description: "Complete UNIX & Linux OS Fundamentals Training — Infosys Springboard",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007911/unix-linux.jpg",
  date: "2026",
},
{
  id: 15,
  title: "Participated IEDC District Cluster Level Hackathon",
  tag: "HACKATHON",
  description: "Participated IEDC District Cluster Level Hackathon — Kerala Startup Mission",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007910/IEDC_District_Cluster_level_Hackathon.jpg",
  date: "2026",
},
{
  id: 16,
  title: "Cyber Security Workshop",
  tag: "WORKSHOP",
  description: "Cyber Security Workshop — Offenso Hackers Academy",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007912/Offenso_Cyber_workshop.jpg",
  date: "2025",
},
{
  id: 17,
  title: "Participated in Hackathon at College of Engineering Attingal",
  tag: "HACKATHON",
  description: "Participated in Hackathon at College of Engineering Attingal — IEEE IA/IE/PELS Jt. Chapter, Kerala",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007910/participation-hackathon-ihrd-attingal.jpg",
  date: "2025",
},
{
  id: 18,
  title: "Participated 20 Hour Hackathon Organized by ISTE TKMCE",
  tag: "HACKATHON",
  description: "Participated 20 Hour Hackathon Organized by ISTE TKMCE — ISTE TKMCE",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007912/Tkm_Hackathon.jpg",
  date: "2025",
},
{
  id: 19,
  title: "Completed 240 Hours Volunteership",
  tag: "VOLUNTEERING",
  description: "Completed 240 Hours Volunteership — Directorate of Technical Education Kerala",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007904/NSS_certificate.jpg",
  date: "2025",
},
{
  id: 20,
  title: "First Place in YUDHYA’25 Hackathon",
  tag: "HACKATHON",
  description: "First Place in YUDHYA’25 Hackathon — μlearn & FOSS Club",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007912/YUDHYA25_HACKATHON.jpg",
  date: "2025",
},
{
  id: 21,
  title: "Participation in CPT HACKS 2024",
  tag: "HACKATHON",
  description: "Participation in CPT HACKS 2024 — IEDC & IIC",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007905/CPT_HACKS.jpg",
  date: "2024",
},
{
  id: 22,
  title: "Participated in BlockHack 2024 (32-Hour Hackathon)",
  tag: "HACKATHON",
  description: "Participated in BlockHack 2024 (32-Hour Hackathon) — Kerala Blockchain Academy",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007901/Block_hack_2024.jpg",
  date: "2024",
},
{
  id: 23,
  title: "AI for Students Workshop",
  tag: "WORKSHOP",
  description: "AI for Students Workshop — NxtWave",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007900/Workshop.jpg",
  date: "2024",
},
{
  id: 24,
  title: "One Month Internship in Python Django",
  tag: "INTERNSHIP",
  description: "One Month Internship in Python Django — Srishti Innovative Computer Systems",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007908/Internship_2.jpg",
  date: "2024",
},
{
  id: 25,
  title: "Participation in Open Hack Event",
  tag: "HACKATHON",
  description: "Participation in Open Hack Event — LBS Institute of Technology for Women",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007904/Open_Hack.png",
  date: "2024",
},
{
  id: 26,
  title: "Webinar on Cybersecurity & Blockchain",
  tag: "WORKSHOP",
  description: "Webinar on Cybersecurity & Blockchain — IIIT Kottayam & Vedhik Academy",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007903/Webinar.png",
  date: "2024",
},
{
  id: 27,
  title: "Volunteer at Attukal Pongala Festival 2024",
  tag: "VOLUNTEERING",
  description: "Volunteer at Attukal Pongala Festival 2024 — District Collector Thiruvananthapuram",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007905/Attukal_2024.jpg",
  date: "2024",
},
{
  id: 28,
  title: "HTML Training Completion",
  tag: "COURSE",
  description: "HTML Training Completion — IIT Bombay",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007901/Spoken_Tutorial.jpg",
  date: "2024",
},
{
  id: 29,
  title: "Cyber Security Workshop Participation",
  tag: "WORKSHOP",
  description: "Cyber Security Workshop Participation — Central Polytechnic College",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007902/Cyber.jpg",
  date: "2023",
},
{
  id: 30,
  title: "International Conclave on Generative AI",
  tag: "WORKSHOP",
  description: "International Conclave on Generative AI — Model Finishing School",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007908/International_Conclave.jpg",
  date: "2023",
},
{
  id: 31,
  title: "Volunteer - Onam Celebrations",
  tag: "VOLUNTEERING",
  description: "Volunteer - Onam Celebrations — Tourism Club Kerala",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007903/Onam.jpg",
  date: "2023",
},
{
  id: 32,
  title: "Beat Plastic Pollution Campaign",
  tag: "VOLUNTEERING",
  description: "Beat Plastic Pollution Campaign — Tourism Mission & Tourism Club Kerala",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007902/Beat_Plastic_Pollution.jpg",
  date: "2023",
},
{
  id: 33,
  title: "Internship in Web Technology",
  tag: "INTERNSHIP",
  description: "Internship in Web Technology — TRINITY Software Technologies",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007910/Internship.jpg",
  date: "2023",
},
{
  id: 34,
  title: "Swachh Bharat Abhiyaan Participation",
  tag: "VOLUNTEERING",
  description: "Swachh Bharat Abhiyaan Participation — Chirak Charitable Society",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007908/Swachh_Bharat_Abhyaan.jpg",
  date: "2023",
},
{
  id: 35,
  title: "Service in Mega Job Fair (Niyukthi 2023)",
  tag: "VOLUNTEERING",
  description: "Service in Mega Job Fair (Niyukthi 2023) — Regional Deputy Director of Employment",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007907/Job_fair.jpg",
  date: "2023",
},
{
  id: 36,
  title: "Volunteer at Attukal Pongala 2023",
  tag: "VOLUNTEERING",
  description: "Volunteer at Attukal Pongala 2023 — District Collector Thiruvananthapuram",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007906/Attukal_2023.jpg",
  date: "2023",
},
{
  id: 37,
  title: "Young Idea Conclave Participation",
  tag: "EVENT",
  description: "Young Idea Conclave Participation — IVAEX & Kerala Startup Mission",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007901/Cet_conclave.png",
  date: "2023",
},
{
  id: 38,
  title: "Participated in 7-Day NSS Camp",
  tag: "VOLUNTEERING",
  description: "Participated in 7-Day NSS Camp — National Service Scheme",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007905/NSS_camp_certificate.jpg",
  date: "2022",
},
{
  id: 39,
  title: "Young Innovators Programme Idea Submission",
  tag: "HACKATHON",
  description: "Young Innovators Programme Idea Submission — K-DISC",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007897/YIP_reg5.0.jpg",
  date: "2022",
},
{
  id: 40,
  title: "Voice of Stakeholder Training (YIP 2022)",
  tag: "EVENT",
  description: "Voice of Stakeholder Training (YIP 2022) — K-DISC",
  image: "https://res.cloudinary.com/ak6fzdkq/image/upload/v1790007898/YIP5.0.jpg",
  date: "2022",
},
];