import { CollectionItem } from './collectionsData';

/**
 * ==============================================================================
 * VIDEOS & FILM REELS DATASET
 * Add or edit your video reels and YouTube videos here.
 * Format:
 * {
 *   id: number,
 *   title: 'Video Title',
 *   tag: 'VERTICAL REEL / CINEMATIC AFTERMOVIE',
 *   description: 'Details',
 *   image: 'https://img.youtube.com/vi/{youtubeId}/hqdefault.jpg',
 *   youtubeId: 'YouTube Video ID',
 *   isVertical: true / false,
 *   duration: '02:30',
 *   date: '2024'
 * }
 * ==============================================================================
 */
export const videosData: CollectionItem[] = [
  {
    id: 1,
    title: 'Cinematic Vertical Reel 01',
    tag: 'VERTICAL REEL',
    description: 'Short-form visual story with dynamic lighting and high-contrast motion editing.',
    image: 'https://img.youtube.com/vi/SyM1EcUYJoA/hqdefault.jpg',
    youtubeId: 'SyM1EcUYJoA',
    isVertical: true,
    duration: '00:30',
    date: '2024',
  },
  {
    id: 2,
    title: 'Creative Mood & Portrait Reel',
    tag: 'CREATIVE SHORT',
    description: 'Atmospheric video snippet exploring dramatic shadows and aesthetic color grading.',
    image: 'https://img.youtube.com/vi/j0HEm5F_bMs/hqdefault.jpg',
    youtubeId: 'j0HEm5F_bMs',
    isVertical: true,
    duration: '00:45',
    date: '2024',
  },
  {
    id: 3,
    title: 'Hult Prize Mainstage Highlights',
    tag: 'EVENT HIGHLIGHT',
    description: 'High-energy vertical short capturing key onstage moments and delegate excitement.',
    image: 'https://img.youtube.com/vi/8tbALWAHJjE/hqdefault.jpg',
    youtubeId: '8tbALWAHJjE',
    isVertical: true,
    duration: '00:50',
    date: '2024',
  },
  {
    id: 4,
    title: 'Urban Fashion & Movement Promo',
    tag: 'FASHION PROMO',
    description: 'Rhythmic fashion promo cut featuring street style aesthetics and fast pacing.',
    image: 'https://img.youtube.com/vi/FalzDaE1MpQ/hqdefault.jpg',
    youtubeId: 'FalzDaE1MpQ',
    isVertical: true,
    duration: '00:40',
    date: '2024',
  },
  {
    id: 5,
    title: 'Behind The Lens & Rig Setup',
    tag: 'BTS SHORT',
    description: 'Behind-the-scenes camera setup, lens switching, and stage direction.',
    image: 'https://img.youtube.com/vi/fLbi7GLsT4Q/hqdefault.jpg',
    youtubeId: 'fLbi7GLsT4Q',
    isVertical: true,
    duration: '00:35',
    date: '2024',
  },
  {
    id: 6,
    title: 'Dynamic Lighting & Slow Motion',
    tag: 'EXPERIMENTAL REEL',
    description: 'Experimental lighting experiment and smooth slow-motion camera movement.',
    image: 'https://img.youtube.com/vi/4wvp9zoHonA/hqdefault.jpg',
    youtubeId: '4wvp9zoHonA',
    isVertical: true,
    duration: '00:45',
    date: '2024',
  },
  {
    id: 7,
    title: 'Night Street & Reflections',
    tag: 'CINEMATIC SHORT',
    description: 'Moody night sequence highlighting street glow and architectural silhouettes.',
    image: 'https://img.youtube.com/vi/g3SuL6ravmA/hqdefault.jpg',
    youtubeId: 'g3SuL6ravmA',
    isVertical: true,
    duration: '00:55',
    date: '2024',
  },
  {
    id: 8,
    title: 'Live Stage Showcase Reel',
    tag: 'DOCUMENTARY SHORT',
    description: 'Stage highlights and crowd interactions captured live during main event.',
    image: 'https://img.youtube.com/vi/IrV78WuoffA/hqdefault.jpg',
    youtubeId: 'IrV78WuoffA',
    isVertical: true,
    duration: '01:00',
    date: '2024',
  },
  {
    id: 9,
    title: 'Hult Prize UCEK Official Aftermovie 2024',
    tag: 'CINEMATIC AFTERMOVIE',
    description: 'Complete 4K cinematic aftermovie capturing keynote presentations, stage lights, and grand finale.',
    image: 'https://img.youtube.com/vi/JcyWqeGmXxo/hqdefault.jpg',
    youtubeId: 'JcyWqeGmXxo',
    isVertical: false,
    duration: '03:12',
    date: '2024',
  },
  {
    id: 10,
    title: 'Visual Director Cut Showreel',
    tag: 'BRAND COMMERCIAL',
    description: 'Compilation of director cuts, brand commercials, and music production reels.',
    image: 'https://img.youtube.com/vi/lEhZN-zqXLo/hqdefault.jpg',
    youtubeId: 'lEhZN-zqXLo',
    isVertical: false,
    duration: '02:30',
    date: '2024',
  },
  {
    id: 11,
    title: 'Full Creative Direction & Production Short',
    tag: 'DOCUMENTARY FILM',
    description: 'Landscape documentary film showcasing comprehensive media production and storytelling.',
    image: 'https://img.youtube.com/vi/Y2j0ip18edI/hqdefault.jpg',
    youtubeId: 'Y2j0ip18edI',
    isVertical: false,
    duration: '04:15',
    date: '2024',
  },
];
